"""empty message

Revision ID: 44fff9d8add4
Revises: c04ae0c4cb24
Create Date: 2023-09-30 13:21:34.572757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44fff9d8add4'
down_revision = 'c04ae0c4cb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('app_name', sa.String(length=200), nullable=False),
    sa.Column('app_country', sa.String(length=200), nullable=False),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_country'),
    sa.UniqueConstraint('app_name')
    )
    op.drop_table('user_app')
    op.drop_table('app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('app_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('current_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('release_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_pkey'),
    sa.UniqueConstraint('app_name', name='app_app_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_app',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_followed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], name='user_app_app_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_app_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'app_id', name='user_app_pkey')
    )
    op.drop_table('app_alert')
    # ### end Alembic commands ###
